---
- hosts: all
  module_defaults:
    ansible.builtin.file:
       pip: pip3
       python: python3
  become: true
  tasks:

      - name: Update the repository index for Ubuntu
        apt:
          update_cache: yes
        when: ansible_distribution == "Ubuntu"

      - name: install packages python3, pip, and java for Ubuntu
        apt:
          name:
             - python3
             - pip
             - openjdk-8-jdk
          state: latest
        when: ansible_distribution == "Ubuntu"

      - name: Update the repository index for CentOS
        dnf:
          update_cache: yes
        when: ansible_distribution == "CentOS"

      - name: install packages python3, pip, and java for CentOS
        dnf:
          name:
             - python3
             - python3-pip
             - java-1.8.0-openjdk
          state: latest
        when: ansible_distribution == "CentOS"

      - name: Make pip as default
        shell: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

      - name: Make python as default
        shell: update-alternatives --install /usr/bin/python python /usr/bin/python3 1
